spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-secret: b8GPVUg21F
            client-id: d3cfMMg9l9u9vrWpPvwM
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            client-authentication-method: client_secret_post
          kakao:
            client-secret: RXW7sQAetcghAz9eFckhbTvHPtpCu5do
            client-id: cc5a1c9ad311c94fa3491ac9448afeb3
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: rud10241024@
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: INFO

security:
  jwt:
    header: Authentication
    issuer: http://auth.example.com
    access-token:
      validity-milliseconds: 36000000
    refresh-token:
      validity-milliseconds: 1209600000
server:
  port: 8081
resource:
  travel-plan: http://localhost:8080
